#! /usr/bin/env ruby

# Get the project name from the first command line argument
project_name = ARGV[0]

# Print usage text if no project name is provided
if project_name.nil?
  puts "Usage: ruby kata <project_name>"
  exit
end

# Create a directory for the project
Dir.mkdir(project_name)

# Create directories for the lib and spec folders
Dir.mkdir("#{project_name}/lib")
Dir.mkdir("#{project_name}/spec")

class_name = project_name.split(/[_-]/).map(&:capitalize).join

# Create an empty file for the main library code
File.write("#{project_name}/lib/#{project_name}.rb", <<~HEREDOC
  # frozen_string_literal: true

  require "pry"

  class #{class_name}
  end
HEREDOC
)

# Create an example spec file
File.write("#{project_name}/spec/#{project_name}_spec.rb", <<~HEREDOC
  # frozen_string_literal: true

  require "pry"
  require "#{project_name}"

  RSpec.describe #{class_name} do
    it "does something" do
      # Test code goes here
    end
  end
HEREDOC
)
